spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:/Users/macpro/Documents/Adrian/sts/spring-guru-workspace
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      
joinfaces:
  jsf:
    PROJECT_STAGE: Production
    FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: saga
  version: @joinfaces.version@
spring-boot:
  version: @project.parent.version@
tomcat:
  version: @tomcat.version@
jetty:
  version: @jetty.version@
undertow:
  version: @undertow.version@
application-users:
  users-credentials:
    - username: persapiens
      password: 123
      authorities: ROLE_ADMIN
    - username: nyilmaz
      password: qwe
      authorities: ROLE_USER
